"""Backend protocol for konsol configuration operations."""
from __future__ import annotations

from typing import Any, Protocol


class ConfigBackend(Protocol):
    def list_dimensions(self, status: str | None = None) -> list[dict[str, Any]]: ...

    def get_dimension(self, name: str) -> dict[str, Any]: ...

    def upsert_dimension(
        self, spec: dict[str, Any], publish: bool = False
    ) -> dict[str, Any]: ...

    def publish_dimension(self, name: str) -> dict[str, Any]: ...

    def unpublish_dimension(self, name: str) -> dict[str, Any]: ...

    def get_measure(self, name: str) -> dict[str, Any]: ...

    def upsert_measure(
        self, spec: dict[str, Any], publish: bool = False
    ) -> dict[str, Any]: ...

    def publish_measure(self, name: str) -> dict[str, Any]: ...

    def unpublish_measure(self, name: str) -> dict[str, Any]: ...

    def apply_schema(self, run_dbt: bool = False) -> dict[str, Any]: ...

    def get_schema_status(self) -> dict[str, Any]: ...

    def list_measures(self, status: str | None = None) -> list[dict[str, Any]]: ...

    def get_fact_table(self, name: str) -> dict[str, Any]: ...

    def upsert_fact_table(
        self, spec: dict[str, Any], publish: bool = False
    ) -> dict[str, Any]: ...

    def publish_fact_table(self, name: str) -> dict[str, Any]: ...

    def unpublish_fact_table(self, name: str) -> dict[str, Any]: ...

    def list_fact_tables(self, status: str | None = None) -> list[dict[str, Any]]: ...

    def list_connectors(self, enabled: bool | None = None) -> list[dict[str, Any]]: ...

    def get_connector(self, name: str) -> dict[str, Any]: ...

    def upsert_connector(self, spec: dict[str, Any]) -> dict[str, Any]: ...

    def delete_connector(self, name: str) -> dict[str, Any]: ...

    def test_connector_writeback(self, name: str) -> dict[str, Any]: ...

    def provision_connector_airbyte(self, name: str) -> dict[str, Any]: ...

    def list_erp_sources(self) -> dict[str, Any]: ...

    def export_config(self, status: str | None = None) -> dict[str, Any]: ...

    def apply_config(
        self, spec: dict[str, Any], publish: bool = False, prune: bool = False
    ) -> dict[str, Any]: ...

    def diff_config(
        self, spec: dict[str, Any], status: str | None = None
    ) -> dict[str, Any]: ...